const { app, BrowserWindow, ipcMain, dialog } = require('electron');
const path = require('path');
const fs = require('fs');
const https = require('https');
const http = require('http');

const isDev = process.env.NODE_ENV !== 'production' || process.argv.includes('--dev');

let mainWindow = null;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1100,
    height: 700,
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  if (isDev) {
    mainWindow.loadURL('http://localhost:5173');
  } else {
    mainWindow.loadFile(path.join(__dirname, '../dist/index.html'));
  }
}

app.whenReady().then(() => {
  createWindow();
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

// Odabir foldera (native dialog, bez native modula)
ipcMain.handle('selectFolder', async () => {
  const { canceled, filePaths } = await dialog.showOpenDialog(mainWindow, {
    properties: ['openDirectory'],
    title: 'Odaberi folder (npr. USB ili disk)',
  });
  if (canceled || !filePaths.length) return null;
  const dirPath = filePaths[0];
  const name = path.basename(dirPath);
  return { path: dirPath, name };
});

// Preuzimanje + EFI na putanju
ipcMain.handle(
  'runAutomation',
  async (_, { dirPath, downloadUrl, fileName, generation }) => {
    const proxyUrl = `https://corsproxy.io/?${encodeURIComponent(downloadUrl)}`;
    const filePath = path.join(dirPath, fileName);

    return new Promise((resolve, reject) => {
      const req = (proxyUrl.startsWith('https') ? https : http).get(proxyUrl, (res) => {
        if (res.statusCode !== 200) {
          reject(new Error(`HTTP ${res.statusCode}`));
          return;
        }
        const total = parseInt(res.headers['content-length'] || '0', 10);
        const file = fs.createWriteStream(filePath);
        let received = 0;
        res.on('data', (chunk) => {
          received += chunk.length;
          if (total > 0 && mainWindow) {
            const pct = Math.floor((received / total) * 100);
            mainWindow.webContents.send('download-progress', pct);
          }
        });
        res.pipe(file);
        file.on('finish', () => {
          file.close(() => {
            try {
              const efiDir = path.join(dirPath, 'EFI', 'OC');
              const subdirs = ['Kexts', 'ACPI', 'Drivers', 'Resources', 'Tools'];
              fs.mkdirSync(efiDir, { recursive: true });
              for (const sub of subdirs) {
                fs.mkdirSync(path.join(efiDir, sub), { recursive: true });
              }
              const configContent = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>#INFO</key>
    <string>Generated by HackinFlow for ${generation}</string>
    <key>ACPI</key><dict><key>Add</key><array/></dict>
    <key>DeviceProperties</key><dict><key>Add</key><dict/></dict>
</dict>
</plist>`;
              fs.writeFileSync(path.join(efiDir, 'config.plist'), configContent);
              resolve({ success: true });
            } catch (err) {
              reject(err);
            }
          });
        });
        file.on('error', reject);
      });
      req.on('error', reject);
    });
  }
);
